### ISSUE TITLE
Is the introduction page of wiki wrong?

### ISSUE THREAD

**Issue by sangyun-han** [kuujo/copycat#31]
![image](https://cloud.githubusercontent.com/assets/11483357/8999741/a9122410-3779-11e5-9199-8c18422d632a.png)

Can I know this is correct?

This image is introduction of cluster in raft github wiki.

there are same IP addr and port numbers.

Is this the scenarios concerning the different cluster nodes in same machine?

**Comment by kuujo** [comment]
It's *definitely* wrong, and not just because of the IP addresses. That documentation has been removed from the README and should have been removed from the wiki. I've deleted the wiki. What's in the master branch is what will be released in the coming weeks, and that is being documented separately. Documentation will go in the README until a release and then it will be moved to the wiki.
