### ISSUE TITLE
Cannot connect CopycatClient

### ISSUE THREAD

**Issue by mikkazan** [kuujo/copycat#33]
Hi All,
I am trying to open connection to Copycat which was started and was running by separate class
sereverId = 1;
host = InetAddress.getLocalHost().getHostName();
port = 8080;

 Members.Builder builder = Members.builder()
                .addMember(new Member(serverId, host, port));
         Copycat copycat = CopycatReplica.builder()
                .withTransport(new NettyTransport())
                .withMemberId(serverId)
                .withMembers(builder.build())
                .withStorage(new Storage())
                .build();
        copycat.open().join();

When I run JUnit test using same parameters as above I get exception that session is not opened 

 Copycat copycatClient = CopycatClient.builder()
                .withTransport(new NettyTransport())
                .withMembers(Members.builder()
                        .addMember(new Member(1, InetAddress.getLocalHost().getHostName(), 8080))
                        .build())
                .build();
       copycatClient.open().thenRun(() -> System.out.println("Successfully connected to the cluster!"));

Am i doing something wrong?

**Comment by mikkazan** [comment]
To be more clear 
this line does not print anything
copycatClient.open().thenRun(() -> System.out.println("Successfully connected to the cluster!"));

So i Broke it into 

 Copycat future = copycatClient.open().get();

 copycatClient.open().thenRun(() -> System.out.println("Successfully connected to the cluster!"));

and here I get session is not open exception

**Comment by kuujo** [comment]
Hey, thanks. This is a bug that's simply due to the fact that we've never been concerned with running Copycat on a single node and therefore seem to have allowed a bug to be introduced on a single node cluster. Because it never requested a vote from another server, the pre-vote protocol never completed. I've committed a fix to force servers to skip elections and immediately transition to `LeaderState` when there are no other members in the cluster, so it should work with a single node now. But I'd obviously never recommend it be used this way.

By the way, Copycat generally has very verbose debug logging. You can enable debug logging (it uses slf4j) to see the internal server communication, state transitions, and other Raft protocol specifics.

Also, my general disclaimer: we're a few weeks away from claiming it behaves well in a distributed environment (after Jepsen testing) but please continue to use and submit bug reports.

Thanks!

**Comment by mikkazan** [comment]
Thanks for explanation. I am trying to start 2 instances on the same machine under different ports and it fails to connect to second server. I am using ServerExample supplied in the master repo of your project. First server started on port 8080
10:45:17.472 [copycat-server-1] INFO  n.k.copycat.io.transport.NettyClient - Connecting to <my_local_host_name>/<my_local_host_ip>:8090
10:45:17.932 [copycat-server-1] DEBUG n.k.copycat.raft.state.FollowerState - 1 - Failed to poll a majority of the cluster in PT0.5S milliseconds
10:45:17.932 [copycat-server-1] DEBUG n.k.copycat.raft.state.FollowerState - 1 - Reset heartbeat timeout
10:45:18.656 [copycat-server-1] DEBUG n.k.copycat.raft.state.FollowerState - 1 - Heartbeat timed out in PT0.723S milliseconds

Is it possible to run two instances os the Copycat on the same machine but 2 different ports. Here is command line args - 1:8080 2:<my_local_host_name>:8090

**Comment by kuujo** [comment]
Hey, so that server example is designed to be run on separate nodes. It uses InetAddress.getLocalHost().getHostName() to get the local server host. So, if you run it the first time you can see the IP that it's binding to and use that as arguments for remote nodes.

What I did is ran it once with the following command:

java -jar server-example.jar 1:5000 2:localhost:5001

When I ran it, it showed the IP that the local server binded to, and I reran both servers with that IP:

java -jar server-example.jar 1:5000 2:123.456.789.0:5001
java -jar server-example.jar 2:5001 1:123.456.789.0:5000

For fault tolerance testing, you'll want at least three nodes, then you can kill -9 nodes at will.

**Comment by mikkazan** [comment]
Understood. Thanks
