### ISSUE TITLE
ReferencePool serialization exception

### ISSUE THREAD

**Issue by mikkazan** [kuujo/copycat#37]
Hi,
My copycat is version 0.6.SNAPSHOT
Trying to start 2 servers on the same machine from 2 different directories and 2 different ports using these commands 
server1
c:\JDK64\1.8.0.45\bin\java -jar copycat-server.jar 1:my_local_host:8080 2:my_local_host:8090
server2 
c:\JDK64\1.8.0.45\bin\java -jar copycat-server.jar 1:my_local_host:8090 2:my_local_host:8080

Got this exception

15/08/31 09:23:24 ERROR concurrent.SingleThreadContext: An uncaught exception occurred
net.kuujo.copycat.io.serializer.SerializationException: failed to serialize Java object
        at net.kuujo.copycat.io.serializer.Serializer.writeSerializable(Serializer.java:625)
        at net.kuujo.copycat.io.serializer.Serializer.writeObject(Serializer.java:549)
        at net.kuujo.copycat.io.transport.NettyConnection.writeRequest(NettyConnection.java:214)
        at net.kuujo.copycat.io.transport.NettyConnection.lambda$send$6(NettyConnection.java:288)
        at net.kuujo.copycat.io.transport.NettyConnection$$Lambda$42/1838865044.run(Unknown Source)
        at net.kuujo.copycat.util.concurrent.SingleThreadContext$1.lambda$execute$9(SingleThreadContext.java:28)
        at net.kuujo.copycat.util.concurrent.SingleThreadContext$1$$Lambda$6/1018547642.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: net.kuujo.copycat.util.ReferencePool
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at net.kuujo.copycat.io.serializer.Serializer.writeSerializable(Serializer.java:620)
        ... 13 more

**Comment by mikkazan** [comment]
Just got latest version from github. Exception still exists....

**Comment by mikkazan** [comment]
Update - had to make PollRequest implements Serializable. Exception is now gone but now servers cannot connect to each other.

**Comment by mikkazan** [comment]
BTW, had to apply serialization to JoinRequest as well as to Member. I think the issue is in Serializer class. It checks if class is  instance of Serializable but those classes were instance of CopycatSerializable. Not sure if it is my local problem and nobody is experiencing same issue.

**Comment by mikkazan** [comment]
Latest update - after I changed domain name to localhost everything worked. But the question regarding serialization of objects remains. Am I missing something or it is the bug?

**Comment by kuujo** [comment]
You should *not* make any internal Copycat classes `Serializable`. Copycat's `Serializer` does fall back to Java serialization when it can't find a serializer for the object, but Java serialization is slow, particularly for something as low level as a `Request` and `Response`. To make those interfaces `Serializable` is to treat the symptom, not the cause.

Copycat's serialization layer is much faster as it does not do any reflection or require serialization of full class names. Instead, it writes a 2-byte class identifier and objects are serialized directly to a `Buffer` by the `CopycatSerializable` class itself or a `TypeSerializer` (see the serialization documentation in the README or the website).

All internal Copycat classes that are written to disk or sent over the wire implement `CopycatSerializable` which has a `readObject` and `writeObject` method (e.g. see https://github.com/kuujo/copycat/blob/master/server/src/main/java/net/kuujo/copycat/raft/protocol/request/PollRequest.java). The problem it seems you're having is that the serializer is not finding the registered classes. By default, serializable classes are registered via Java's `ServiceLoader` API (those request/response classes are registered at https://github.com/kuujo/copycat/blob/master/protocol/src/main/resources/META-INF/services/net.kuujo.copycat.io.serializer.CopycatSerializable and https://github.com/kuujo/copycat/blob/master/server/src/main/resources/META-INF/services/net.kuujo.copycat.io.serializer.CopycatSerializable). This allows the `Serializer` to map a serializable type `id` to a `Class` during deserialization.

The original stack trace you posted implies that the serializer for some reason thought the class was not `CopycatSerializable`. The likely case was that the service loader did not pick up the file(s) I linked above for some reason, or it could be a bug wherein the `ServiceLoaderTypeResolver` is never added to the `Serializer`, and since `Request` is not `Serializable` it failed (as it should have). Alternatively, there is some potential that if two serializable types use the same type `id`, one will override the other. I'll investigate this. Which artifacts were you using? I'm wondering if there is a serializable type `id` conflict that doesn't occur in tests because modules are tested separately.

**Comment by mikkazan** [comment]
I am using the latest version. I believe it's 1.0.0-SNAPSHOT.

**Comment by mikkazan** [comment]
Some miracle happened. I reverted back my changes, moved jar files into directories  under my user and serialization error went away. Before the directories were under c: drive.
But test to read value form copycat is constantly failing although servers are up 

@Test
    public final void receiveMessageTest() throws InterruptedException, ExecutionException, UnknownHostException {
        String key = "test-map";
        Members members = Members.builder()
                .addMember(new Member(1, "localhost", 8080))
                .addMember(new Member(2, "localhost", 8090))
                .build();
        Copycat copycatClient = CopycatClient.builder(members)
                .withTransport(new NettyTransport())
                .build();
        copycatClient.open().thenRun(() -> {
            System.out.println("Client connected!");
        });
       
        DistributedMap map = copycatClient.get(key, DistributedMap.class).get();
        System.out.println("Value in Server " + map.get("test-1-key"));

        if (copycatClient.isClosed()) {
            System.out.println("receiveMessageTest: Client is already closed ");
        } else {
            System.out.println("Closing client");
            copycatClient.close();
        }
    }

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client not open
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at MessageTest.receiveMessageTest(MessageTest.java:67)



What am I doing wrong. Sorry I couldn't find proper docs how to read data.

**Comment by kuujo** [comment]
Asynchronous programming is something that takes getting used to. You need to move your DistributedMap code *inside* the `open()` callback or block to wait for the client to connect.

If you put print statements in your code both inside of the `open()` callback and below the `open()` callback, you'll see that the code *below* the callback is run in the main thread before the code *inside* the callback is run on a Copycat thread. Basically, in asynchronous programming you cannot think of programs executing from top to bottom. Instead, programs execute from callback to callback.

http://stackoverflow.com/questions/16336367/what-is-the-difference-between-synchronous-and-asynchronous-programming-in-node

But for simplicity, you can force futures to block and therefore expect programs to execute from top to bottom. Just replace the `open()` callback with `get()` or `join()` instead of `thenRun(...)`. This will force the thread to wait for the client to connect to the server before moving on to the next line of code.

You should definitely use the blocking `get` and `join` `Future` methods if you're not used to asynchronous programming. The reason for the asynchronous API is this:
When a client writes to the cluster, the client makes a request to the server to which it's connected, which makes a request to the leader, which logs the write to disk and then replicates it to a majority of the followers, then the leader responds to the server that forwarded the client's request, and finally the server responds to the client. When you block with `get()` or `join()` your thread is blocked while all that communication is taking place, and that can take a not insignificant amount of time. This may be acceptable for many applications, but for others, they have the option of using the asynchronous API. When using the asynchronous API, the user makes a call to a Copycat API and the program continues. This allows clients to submit many reads and writes concurrently, and Copycat will handle them in the order in which they were sent. So, a client can `put` 10 keys in the same map, and each of those changes will be handled concurrently by the Copycat cluster. One write may be on its way to the leader, while another may have already been logged and is in the process of being replicated. The asynchronous APIs maximizes throughout by allowing many concurrent operations from the same client.

In the case of your code, you're calling `open()` and registering an asynchronous callback *to be called on another thread once the client has connected to the server and registered a new session.* Then, since the calling thread is not blocked, the thread continues on to `get` the `DistributedMap`. But since the thread was not blocked and the `Copycat.get` call was not made inside the `open()` callback, the client *is not yet open* and therefore it throws an exception.

Add `join()` after `copycatClient.open()` - `copycatClient.open().join();` - instead of `thenRun(...)` and you should be fine.

**Comment by mikkazan** [comment]
Thanks for the answer. 
I did this 
System.out.println("running sendMessageTest");
Members members = Members.builder()
                .addMember(new Member(1, "localhost", 8080))
                .addMember(new Member(2, "localhost", 8090))
                .build();
Copycat copycatClient = CopycatClient.builder(members)
                .withTransport(new NettyTransport())
                .build();
        String key = "test-map";
        copycatClient.open().join();
        Thread.sleep(1000);

But get this now 

15/09/01 09:58:16 WARN session.ClientSession: Failed to connect to cluster

Could you give me the name of the tests which have message insertion and message retrieval? I had to disable test due to the fact that lots of them were failing while running the build.
Thanks,

**Comment by kuujo** [comment]
Because the Transport is pluggable, all of the tests for the most part use LocalTransport to avoid having to create clients and servers for each test. Here are the DistributedMap tests:
https://github.com/kuujo/copycat/blob/master/collections/src/test/java/net/kuujo/copycat/collections/DistributedMapTest.java

You should be able to replace the LocalTransport in that test case with NettyTransport and see them work.

For network testing, the Jepsen tests use a cluster of 5 docker containers which use NettyTransport to communicate with one another:
https://github.com/jhalterman/copycat-jepsen

Jepsen tests cover a variety of failure scenarios including all manner of network partitions and server crashes.

BTW you don't have to call Thread.sleep(1000)... When you call copycatClient.open().join(), the join() is basically forcing the thread to block until the client is open.

**Comment by mikkazan** [comment]
I'm sorry but I still struggle with it.

String host = null;
        try {
            host = InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(MessageTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        Members members = Members.builder()
                .addMember(new Member(1, host, 8080))
                .addMember(new Member(2, host, 8090))
                .build();
        Copycat copycatClient = CopycatClient.builder(members)
                .withTransport(new NettyTransport())
                .build();
//        copycatClient.open().thenRun(() -> 
//  I took this snippet from the README
        copycatClient.create("/test-map", DistributedMap.class).thenAccept(map -> {
                    map.put("key", "value").thenRun(() -> {
                        map.get("key").thenAccept(value -> {
                            if (value.equals("value")) {
                                try {
                                    // Set a key with a TTL
                                    map.putIfAbsent("otherkey", "othervalue", Duration.ofSeconds(1)).get();
                                    System.out.println("Finished operating with map");
                                } catch (InterruptedException | ExecutionException ex) {
                                    Logger.getLogger(MessageTest.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        });
                    });
                });
        //);

But it is not even connecting to 2 copycat servers which I have running. Here is test log

running sendMessageTest
15/09/02 14:24:58 DEBUG logging.InternalLoggerFactory: Using SLF4J as the default logging framework
15/09/02 14:24:58 DEBUG channel.MultithreadEventLoopGroup: -Dio.netty.eventLoopThreads: 24
15/09/02 14:24:58 DEBUG internal.PlatformDependent0: java.nio.Buffer.address: available
15/09/02 14:24:58 DEBUG internal.PlatformDependent0: sun.misc.Unsafe.theUnsafe: available
15/09/02 14:24:58 DEBUG internal.PlatformDependent0: sun.misc.Unsafe.copyMemory: available
15/09/02 14:24:58 DEBUG internal.PlatformDependent0: java.nio.Bits.unaligned: true
15/09/02 14:24:58 DEBUG internal.PlatformDependent: Platform: Windows
15/09/02 14:24:58 DEBUG internal.PlatformDependent: Java version: 8
15/09/02 14:24:58 DEBUG internal.PlatformDependent: -Dio.netty.noUnsafe: false
15/09/02 14:24:58 DEBUG internal.PlatformDependent: sun.misc.Unsafe: available
15/09/02 14:24:58 DEBUG internal.PlatformDependent: -Dio.netty.noJavassist: false
15/09/02 14:24:58 DEBUG internal.PlatformDependent: Javassist: unavailable
15/09/02 14:24:58 DEBUG internal.PlatformDependent: You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
15/09/02 14:24:58 DEBUG internal.PlatformDependent: -Dio.netty.tmpdir: C:\Users\MyUser\AppData\Local\Temp (java.io.tmpdir)
15/09/02 14:24:58 DEBUG internal.PlatformDependent: -Dio.netty.bitMode: 64 (sun.arch.data.model)
15/09/02 14:24:58 DEBUG internal.PlatformDependent: -Dio.netty.noPreferDirect: false
15/09/02 14:24:58 DEBUG nio.NioEventLoop: -Dio.netty.noKeySetOptimization: false
15/09/02 14:24:58 DEBUG nio.NioEventLoop: -Dio.netty.selectorAutoRebuildThreshold: 512
Tests run: 3, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 1.41 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 2

Notice that System.out.println didn't even print anything into the console. Sorry for bothering you that much but DistributedMapTest is using CopyCatReplica builder not CopycatClient and I am trying to make message submission and retreival working using CopycatC lient.

**Comment by kuujo** [comment]
This conversation should be moved to [the Google group](https://groups.google.com/forum/m/#!forum/copycat) (repost it there)

**Comment by kuujo** [comment]
But to answer your question, if that is the full code in your test method, the test is completing *before* the client is ever connecting to the server. As I mentioned before, if you're not familiar with asynchronous programming, you should stick with the blocking `get()` and `join()` methods. 

The main thread in your test is doing this:
```java
copycatClient.create("/test-map", DistributedMap.class).thenAccept(...)
```

What his code says is, "create a `DistributedMap` and then call the `Consumer` registered in `thenAccept`." What it notably does *not* say is, block until the `DustributedMap` has been created. So, what is happening is this:
`copycatCliebt.create...)` is called in the `main` thread. Internally, Copycat queues the call on an *internal* `copycat-*` thread, and the `main` thread continues until it reaches the end of the test. So, your test is ending before the `create(...)` is ever sent to the cluster before you are making an *asynchronous* call rather than a *synchronous* call. As I mentioned, with asynchronous programming you cannot expect programs to execute from top to bottom. But the `main` thread *will* continue to execute from top to bottom, so if you put `Thread.sleep(10000)` at the bottom of your test or use blocking calls with *all* futures by calling `get()` or `join()` then your test will complete. Each time you use `thebRun(...)` or `thenAccept(...)` or `whenComplete(...)` you should assume that the code *after* the call will be executed *before* the code inside the callback. This is what makes it asynchronous. You are saying, "keep executing my program from top to bottom, and whenever the `create(...)` call finishes or the `put(...)` call finishes, call the callback created in `thenAccept(...)` or `thenRun(...)` on a different thread. Hence, you have to block the calling thread if you want to wait for those callbacks to run before your test finishes.

**Comment by kuujo** [comment]
Look at this test: https://github.com/kuujo/copycat/blob/master/collections/src/test/java/net/kuujo/copycat/collections/DistributedMapTest.java

Everywhere where it says `await()`, it is saying "block the thread until the above callback has been called" and that's what you have to do (or just use `get` or `join`) if you want the things inside the callbacks to happen before the `main` thread reaches the end of the method

**Comment by kuujo** [comment]
```
DistributedMap<String, String> map = copycatClient.create("test", DistributedMap.class).get();

map.put("foo", "bar").join();

assert map.get("foo").get().equals("bar");
```

Note that I called `get()` or `join()` on each call. This causes it to block and behave like the operation happens instantaneously (which it doesn't). This is what you should do if you don't need concurrency for a client (don't need many `put`s from a client being processed at the same time).
