### ISSUE TITLE
Building a distributed sqlite database with copycat

### ISSUE THREAD

**Issue by tchoulihan** [kuujo/copycat#39]
Hey @kuujo , glad to see the new rework of copycat, it looks great!

So I'm considering attempting to build a distributed sqlite db on top of copycat, and probably in particular, its collections framework.

My main question, is that I want clients to **automatically** get/query a shared collection, and then be able to insert any new data into their own sqlite DB. 

What would be the best way to do this with copycat? Is there any way to asynchronously **send** messages to the rest of the raft peers, and they receive them on a listener, and update their own distributed maps/sets? Or just create a listener that receives all new puts to a distributed map or set?

Thanks in advance.

**Comment by kuujo** [comment]
Alright. So, basically there are now a few of ways you can go about this, and it really depends on your use case.

The first and most low-level option is to actually create a persistent Raft state machine and a custom `Resource`. Resources like `DistributedMap` are really just in-memory state machines with a client API. Writing state changes to an SQLite database simply makes it a persistent state machine. So, what you would do is extend `Resource` and create a `StateMachine` which registers a `Command` that contains the data you want to be replicated and written to SQLite. Then, create a Copycat cluster and create an instance of the resource with `copycat.create("foo", MyResourceClass.class)`. When a resource is created, Copycat creates an instance of the resource's state machine on each `CopycatReplica`. When the resource `submit`s commands to the cluster, the commands are replicated and guaranteed to eventually be applied to the state machine on each replica. So, your state machine would just have a command method that writes the command to SQLite and then `clean()`s the command from the log:

```
private void writeToSqlite(Commit<WriteCommand> commit) {
  // write the data
  // clean the commit
  commit.clean();
}
```

Calling `commit.clean()` on the commit after its written to SQLite will cause Copycat to eventually remove it from the Raft log. Note, however, that it's not *immediately* removed from disk. It could take some time for the commit to be cleaned from the log, so in the event of a crash and recovery, when Copycat replays the log it will reapply it to the state machine. For this reason, you should store the `commit.index()` in SQLite with the data and use it to deduplicate commands as they're written to SQLite. Commit indexes are monotonically increasing, so you just need to check to ensure that no index >= `commit.index()` has been written to SQLite to deduplicate the commits. This deduplication requirement is just a requirement of exactly-once semantics required by persistent state machines.

Alternatively, much of the refactoring that has gone into the pending Copycat release was centered on allowing state machines to push data to clients. Copycat now has the concept of sessions which represent a fault tolerant connection between a client and the entire Raft cluster. Sessions allow state machines to *push* data to clients rather than requiring clients to poll the cluster for changes. This was essentially created as a replacement of asynchronous replication. 

An example of using sessions for messaging between clients is the `DistributedTopic` resource. What the distributed topic does is allows clients to subscribe to receive messages sent to the topic resource by other clients. When a message is published to a topic, once the message is received and replicated by the Raft cluster, it's guaranteed to eventually be sent to all subscribed clients so long as their sessions remain open. Internally, sessions have logic to ensure sequence and deduplicate events sent by state machines and ensure that each client/session receives all events in the same order in which they occur in the Raft state machines. This mechanism can be used to essentially replicate state changes from one client to another. But the caveat is that when a client dies, it stops receiving state changes.

The addition of sessions is a powerful feature, but I would recommend the custom resource/state machine approach right now only because Copycat's resource implementations like `DistributedTopic` are too immature to account for things like persisting state changes through client failures. But the resources that Copycat does provide are great examples. I would recommend looking at the `DistributedTopic` resource. All you may need is a single command that writes to an SQLite database and then cleans the commit (which is very important). Note, though, that there's currently a limitation in configuring resources/state machines that I think you'll notice. Resources are not currently configurable, and the API only accepts class objects, so something like providing a database configuration will require the use of system properties or something like that. I have explored options for configuring resources when they're created, but there is some complexity in that since resources can be created my multiple clients and therefore configurations must be somehow prioritized. But I digress. Maybe I'll experiment with resource/state machine configurations a bit more.

**Comment by tchoulihan** [comment]
Thanks Jordan, this is really helpful.

It looks like the main caveats are :
1) Create a commit_index table as part of the sqlite db, and make sure that
only commands after your own most recent commit index, when you receive
raft messages. This table could be cleared out periodically too.

Question, wouldn't it be better to base the commit index on
getSystemMillis(), rather than on an autogenerated id field?

I could see duplicated commit indices potentially happening if two clients
are both up to date, then do a sql write/update command. This could be
mitigated using system time.

2) Create a custom resource that contains a write command, and run
commit.clean().

Question about this: it only removes it from the raft log after 100% of the
clients have received the command, correct? Otherwise, it might be removed
before all clients get a chance to write it.

3) Subscribe each client to a distributedtopic, using it to listen and
write any commands to their own dbs. Isn't this the place where that
writeToSqlite method below would be?

Thanks.

**Comment by kuujo** [comment]
Hey, I'm gonna move this to the [Google group](https://groups.google.com/forum/m/#!forum/copycat)

[Here's the topic](https://groups.google.com/forum/m/#!topic/copycat/2JVTI9ia7yo) to which I'll respond there (I'm trying to move these questions to the group now... let me know if you have trouble accessing it)
